export const customLinkPropsDocs = [
  {
    prop: 'to',
    type: 'string',
    required: true,
    description: 'URL для перехода. Может быть относительным путем, полным URL или якорем (#section)',
    defaultValue: '-',
  },
  {
    prop: 'children',
    type: 'React.ReactNode',
    required: true,
    description: 'Текст или содержимое ссылки',
    defaultValue: '-',
  },
  {
    prop: 'variant',
    type: "'default' | 'primary' | 'secondary' | 'muted'",
    required: false,
    description: 'Вариант стилизации ссылки:',
    details: [
      '• default - стандартная ссылка',
      '• primary - акцентный цвет темы',
      '• secondary - второстепенная ссылка',
      '• muted - приглушенный вариант'
    ],
    defaultValue: "'default'",
  },
  {
    prop: 'size',
    type: "'sm' | 'md' | 'lg'",
    required: false,
    description: 'Размер текста ссылки',
    defaultValue: "'md'",
  },
  {
    prop: 'underline',
    type: 'boolean',
    required: false,
    description: 'Показывать ли подчеркивание у ссылки',
    defaultValue: 'false',
  },
  {
    prop: 'className',
    type: 'string',
    required: false,
    description: 'Дополнительные CSS классы',
    defaultValue: '-',
  },
  {
    prop: 'external',
    type: 'boolean',
    required: false,
    description: 'Если true, ссылка откроется в новой вкладке (использует тег <a>)',
    defaultValue: 'false',
  },
  {
    prop: 'nav',
    type: 'boolean',
    required: false,
    description: 'Использовать NavLink для отслеживания активного состояния',
    defaultValue: 'false',
  },
  {
    prop: 'smoothScroll',
    type: 'boolean',
    required: false,
    description: 'Включить плавную прокрутку для якорей на текущей странице',
    defaultValue: 'true',
  },
  {
    prop: 'scrollOffset',
    type: 'number',
    required: false,
    description: 'Смещение в пикселях при прокрутке к якорю (полезно для фиксированных хедеров)',
    defaultValue: '0',
  },
];
