export const gridPropsDocs = [
  {
    prop: 'children',
    type: 'React.ReactNode',
    required: true,
    description: 'Дочерние элементы Grid. Обычно GridItem компоненты или другие React элементы',
    defaultValue: '-',
  },
  {
    prop: 'cols',
    type: '1 | 2 | 3 | 4 | 5 | 6',
    required: false,
    description: 'Количество колонок по умолчанию (на мобильных устройствах)',
    defaultValue: '1',
  },
  {
    prop: 'sm',
    type: '1 | 2 | 3 | 4 | 5 | 6',
    required: false,
    description: 'Количество колонок на экранах small (≥640px)',
    defaultValue: '-',
  },
  {
    prop: 'md',
    type: '1 | 2 | 3 | 4 | 5 | 6',
    required: false,
    description: 'Количество колонок на экранах medium (≥768px)',
    defaultValue: '-',
  },
  {
    prop: 'lg',
    type: '1 | 2 | 3 | 4 | 5 | 6',
    required: false,
    description: 'Количество колонок на экранах large (≥1024px)',
    defaultValue: '-',
  },
  {
    prop: 'xl',
    type: '1 | 2 | 3 | 4 | 5 | 6',
    required: false,
    description: 'Количество колонок на экранах extra large (≥1280px)',
    defaultValue: '-',
  },
  {
    prop: 'gap',
    type: "'none' | 'sm' | 'md' | 'lg' | 'xl'",
    required: false,
    description: 'Расстояние между элементами Grid. Контролирует gutter spacing',
    defaultValue: "'md'",
  },
  {
    prop: 'as',
    type: "'div' | 'section' | 'ul'",
    required: false,
    description: 'HTML тег для рендеринга. Используйте ul для списков, section для семантических разделов',
    defaultValue: "'div'",
  },
  {
    prop: 'className',
    type: 'string',
    required: false,
    description: 'Дополнительные CSS классы для кастомизации Grid контейнера',
    defaultValue: '-',
  },
];

export const gridItemPropsDocs = [
  {
    prop: 'children',
    type: 'React.ReactNode',
    required: true,
    description: 'Содержимое GridItem',
    defaultValue: '-',
  },
  {
    prop: 'span',
    type: '1 | 2 | 3 | 4 | 5 | 6 | "full"',
    required: false,
    description: 'Количество колонок, которые занимает элемент по умолчанию',
    defaultValue: '-',
  },
  {
    prop: 'sm',
    type: '1 | 2 | 3 | 4 | 5 | 6 | "full"',
    required: false,
    description: 'Размер на экранах small (≥640px)',
    defaultValue: '-',
  },
  {
    prop: 'md',
    type: '1 | 2 | 3 | 4 | 5 | 6 | "full"',
    required: false,
    description: 'Размер на экранах medium (≥768px)',
    defaultValue: '-',
  },
  {
    prop: 'lg',
    type: '1 | 2 | 3 | 4 | 5 | 6 | "full"',
    required: false,
    description: 'Размер на экранах large (≥1024px)',
    defaultValue: '-',
  },
  {
    prop: 'xl',
    type: '1 | 2 | 3 | 4 | 5 | 6 | "full"',
    required: false,
    description: 'Размер на экранах extra large (≥1280px)',
    defaultValue: '-',
  },
  {
    prop: 'as',
    type: "'div' | 'li' | 'article'",
    required: false,
    description: 'HTML тег для рендеринга. Используйте li для элементов списка',
    defaultValue: "'div'",
  },
  {
    prop: 'className',
    type: 'string',
    required: false,
    description: 'Дополнительные CSS классы для кастомизации GridItem',
    defaultValue: '-',
  },
];
